### PR TITLE
applications: Fix sandbox detection

### PR DESCRIPTION
**Pull request by tchx84**
FLATPAK_ID is only available to apps from Flatpak v1.1.2

### CODE REVIEW

**Comment by tchx84** [comment]
@dlalinsp can you help me test this?

Run these commands from terminal one by one:

```
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
git checkout fix-sandbox-detection
flatpak --system install flathub org.gnome.Sdk//3.38
flatpak --system install flathub org.gnome.Platform//3.38
flatpak-builder --force-clean --repo=repo build com.github.tchx84.Flatseal.json
flatpak build-bundle repo flatseal.flatpak com.github.tchx84.Flatseal
flatpak install flatseal.flatpak
flatpak run com.github.tchx84.Flatseal//master
```

EDIT: Added the install step, ops!

**Comment by ghost** [comment]
I think something went wrong with the last few commands.

```
dlalinsp@Vortex-Blackbox:~$ cd Downloads

dlalinsp@Vortex-Blackbox:~/Downloads$ git clone https://github.com/tchx84/Flatseal.git
Cloning into 'Flatseal'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 2183 (delta 47), reused 46 (delta 30), pack-reused 2097
Receiving objects: 100% (2183/2183), 10.89 MiB | 2.93 MiB/s, done.
Resolving deltas: 100% (1452/1452), done.

dlalinsp@Vortex-Blackbox:~/Downloads$ cd Flatseal

dlalinsp@Vortex-Blackbox:~/Downloads/Flatseal$ git checkout fix-sandbox-detection
Branch 'fix-sandbox-detection' set up to track remote branch 'fix-sandbox-detection' from 'origin'.
Switched to a new branch 'fix-sandbox-detection'

dlalinsp@Vortex-Blackbox:~/Downloads/Flatseal$ flatpak --system install flathub org.gnome.Sdk//3.38
Skipping: org.gnome.Sdk/x86_64/3.38 is already installed

dlalinsp@Vortex-Blackbox:~$ flatpak --system install flathub org.gnome.Platform//3.38
Skipping: org.gnome.Platform/x86_64/3.38 is already installed


dlalinsp@Vortex-Blackbox:~/Downloads/Flatseal$ flatpak-builder --force-clean --repo=repo build com.github.tchx84.Flatseal.json 
Downloading sources
Downloading https://download.gnome.org/sources/libhandy/1.0/libhandy-1.0.2.tar.xz
Downloading https://github.com/hughsie/appstream-glib/archive/appstream_glib_0_7_18.tar.gz
Downloading https://github.com/ptomato/jasmine-gjs/releases/download/2.6.4/jasmine-gjs-2.6.4.tar.xz
Initialized empty Git repository in /home/dlalinsp/Downloads/Flatseal/.flatpak-builder/git/_home_dlalinsp_Downloads_Flatseal-OYYNU0/
Fetching git repo /home/dlalinsp/Downloads/Flatseal, ref HEAD
remote: Counting objects: 171, done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 171 (delta 39), reused 104 (delta 11)
Receiving objects: 100% (171/171), 1.81 MiB | 66.34 MiB/s, done.
Resolving deltas: 100% (39/39), done.
From /home/dlalinsp/Downloads/Flatseal
 * [new ref]                    -> HEAD
Initializing build dir
Committing stage init to cache
Starting build of com.github.tchx84.Flatseal
========================================================================
Building module libhandy in /home/dlalinsp/Downloads/Flatseal/.flatpak-builder/build/libhandy-1
========================================================================
The Meson build system
Version: 0.55.3
Source dir: /run/build/libhandy
Build dir: /run/build/libhandy/_flatpak_build
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Project name: libhandy
Project version: 1.0.2
Using 'LDFLAGS' from environment with value: '-L/app/lib '
Using 'LDFLAGS' from environment with value: '-L/app/lib '
C compiler for the host machine: ccache cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wdate-time: YES 
Compiler for C supports arguments -Wdeclaration-after-statement: YES 
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Werror=missing-declarations: YES 
Compiler for C supports arguments -Werror=overflow: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=shift-count-overflow: YES 
Compiler for C supports arguments -Werror=shift-overflow=2: YES 
Compiler for C supports arguments -Werror=implicit-fallthrough=3: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmaybe-uninitialized: YES 
Compiler for C supports arguments -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-missing-field-initializers -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wno-sign-compare -Wsign-compare: YES 
Compiler for C supports arguments -Wno-strict-aliasing -Wstrict-aliasing: YES 
Compiler for C supports arguments -Wno-unused-parameter -Wunused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wswitch-default: YES 
Compiler for C supports arguments -Wswitch-enum: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wunused-function: YES 
Compiler for C supports arguments -fstack-protector-strong: YES 
Dependency gladeui-2.0 skipped: feature glade_catalog disabled
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Configuring hdy-version.h using configuration
Program glib-mkenums found: YES
Program glib-mkenums found: YES
Program sed found: YES
Program gen-public-types.sh found: YES
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Run-time dependency glib-2.0 found: YES 2.66.1
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Run-time dependency gio-2.0 found: YES 2.66.1
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Run-time dependency gmodule-2.0 found: YES 2.66.1
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Run-time dependency gtk+-3.0 found: YES 3.24.23
Library m found: YES
Library rt found: YES
Configuring config.h using configuration
Checking if "ld_supports_version_script" links: YES 
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Build-time dependency gobject-introspection-1.0 found: YES 1.66.1
Program g_ir_scanner found: YES (/usr/bin/g-ir-scanner)
Program g_ir_compiler found: YES (/usr/bin/g-ir-compiler)
Configuring run using configuration
Message: 
------
Handy 0 (1)

             Tests: false
          Examples: false
     Documentation: false
     Introspection: true
              Vapi: false
     Glade Catalog: false
------

Build targets in project: 13

Found ninja-1.10.1 at /usr/bin/ninja
[59/59] Generating Handy-1.typelib with a custom command
[0/1] Installing files.
Installing src/hdy-enums.h to /app/include/libhandy-1
Installing src/libhandy-1.so.0 to /app/lib/
Installing src/Handy-1.gir to /app/share/gir-1.0
Installing src/Handy-1.typelib to /app/lib/girepository-1.0
Installing /run/build/libhandy/src/handy.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-action-row.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-animation.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-application-window.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-avatar.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-carousel.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-carousel-indicator-dots.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-carousel-indicator-lines.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-clamp.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-combo-row.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-deck.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-deprecation-macros.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-enum-value-object.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-expander-row.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-header-bar.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-header-group.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-keypad.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-leaflet.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-main.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-navigation-direction.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-preferences-group.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-preferences-page.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-preferences-row.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-preferences-window.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-search-bar.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-squeezer.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-swipe-group.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-swipe-tracker.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-swipeable.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-title-bar.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-types.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-value-object.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-view-switcher.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-view-switcher-bar.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-view-switcher-title.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-window.h to /app/include/libhandy-1
Installing /run/build/libhandy/src/hdy-window-handle.h to /app/include/libhandy-1
Installing /run/build/libhandy/_flatpak_build/src/hdy-version.h to /app/include/libhandy-1
Installing /run/build/libhandy/_flatpak_build/meson-private/libhandy-1.pc to /app/lib/pkgconfig
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=libhandy'
Installing /run/build/libhandy/_flatpak_build/po/ca.gmo to /app/share/locale/ca/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/en_GB.gmo to /app/share/locale/en_GB/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/es.gmo to /app/share/locale/es/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/eu.gmo to /app/share/locale/eu/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/fr.gmo to /app/share/locale/fr/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/fur.gmo to /app/share/locale/fur/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/id.gmo to /app/share/locale/id/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/pl.gmo to /app/share/locale/pl/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/pt_BR.gmo to /app/share/locale/pt_BR/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/ro.gmo to /app/share/locale/ro/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/sl.gmo to /app/share/locale/sl/LC_MESSAGES/libhandy.mo
Installing /run/build/libhandy/_flatpak_build/po/uk.gmo to /app/share/locale/uk/LC_MESSAGES/libhandy.mo
compressing debuginfo in: /home/dlalinsp/Downloads/Flatseal/.flatpak-builder/rofiles/rofiles-HcknJg/files/lib/libhandy-1.so.0
Warning: eu-elfcompress not installed, will not compress debuginfo
stripping /home/dlalinsp/Downloads/Flatseal/.flatpak-builder/rofiles/rofiles-HcknJg/files/lib/libhandy-1.so.0 to /home/dlalinsp/Downloads/Flatseal/.flatpak-builder/rofiles/rofiles-HcknJg/files/lib/debug/lib/libhandy-1.so.0.debug
Error: module libhandy: Failed to execute child process “eu-strip” (No such file or directory)


dlalinsp@Vortex-Blackbox:~/Downloads/Flatseal$ flatpak build-bundle repo flatseal.flatpak com.github.tchx84.Flatseal
error: 'repo' is not a valid repository

dlalinsp@Vortex-Blackbox:~/Downloads/Flatseal$ flatpak install flatseal.flatpak
error: Failed to open file “/home/dlalinsp/Downloads/Flatseal/flatseal.flatpak”: open() failed: No such file or directory

dlalinsp@Vortex-Blackbox:~/Downloads/Flatseal$ flatpak run com.github.tchx84.Flatseal//master
error: app/com.github.tchx84.Flatseal/x86_64/master not installed

```

**Comment by tchx84** [comment]
@dlalinsp I found a previous report (from another app) with the exact same issue, maybe you can try what they suggest there: https://github.com/flathub/com.anydesk.Anydesk/issues/22#issuecomment-560343695

**Comment by ghost** [comment]
> @dlalinsp I found a previous report (from another app) with the exact same issue, maybe you can try what they suggest there: [flathub/com.anydesk.Anydesk#22 (comment)](https://github.com/flathub/com.anydesk.Anydesk/issues/22#issuecomment-560343695)

Installing `elfutils` on my system did the trick. Thanks! I am also happy to report that I can now modify permissions via Flatseal and it does not crash anymore. :smile: 

P.S. How do I get rid of the version I installed from source?

**Comment by tchx84** [comment]
> > @dlalinsp I found a previous report (from another app) with the exact same issue, maybe you can try what they suggest there: [flathub/com.anydesk.Anydesk#22 (comment)](https://github.com/flathub/com.anydesk.Anydesk/issues/22#issuecomment-560343695)
> 
> Installing `elfutils` on my system did the trick. Thanks! I am also happy to report that I can now modify permissions via Flatseal and it does not crash anymore. 
> 
> P.S. How do I get rid of the version I installed from source?

Well, I recommend you keep it... because I am going to make a new release with this fix, so you won't need this "custom" version after that one updates.

When you see Flatseal updates to 1.6.5, means you can uninstall the "custom" version using `flatpak uninstall com.github.tchx84.Flatseal//master`

**Comment by ghost** [comment]
> > > @dlalinsp I found a previous report (from another app) with the exact same issue, maybe you can try what they suggest there: [flathub/com.anydesk.Anydesk#22 (comment)](https://github.com/flathub/com.anydesk.Anydesk/issues/22#issuecomment-560343695)
> > 
> > 
> > Installing `elfutils` on my system did the trick. Thanks! I am also happy to report that I can now modify permissions via Flatseal and it does not crash anymore.
> > P.S. How do I get rid of the version I installed from source?
> 
> Well, I recommend you keep it... because I am going to make a new release with this fix, so you won't need this "custom" version after that one updates.
> 
> When you see Flatseal updates to 1.6.5, means you can uninstall the "custom" version using `flatpak uninstall com.github.tchx84.Flatseal//master`

Thanks! I appreciate it. Have a great day!

**Pull request merged**
