### PR TITLE
pathRow: Set !(negation) prefix as valid

### LINKED ISSUE #314: Flatseal shows valid filesystem settings as invalid
Telegram has recently added a setting like ```!~/.TelegramDesktop``` but Flatseal shows it as an invalid option where it should be something valid. 

Also see: https://github.com/flathub/org.telegram.desktop/issues/310#issuecomment-911491628

Screenshot from 2021-09-02 12-54-35

### PR DESCRIPTION
**Pull request by tchx84**
Closes #314

### CODE REVIEW

**Comment by tchx84** [comment]
@xscd @gasinvein can you help me test this? try to break it :pray:

**Comment by gasinvein** [comment]
Seems to behave properly, i.e. removing the negated entry adds the un-negated entry to overrides, and adding it back removes the override.

**Comment by gasinvein** [comment]
Hmm, a proper tooltip for such entries seems missing, currently the tolltip says `Can modify and read:`

**Comment by tchx84** [comment]
> Hmm, a proper tooltip for such entries seems missing, currently the tolltip says `Can modify and read:`

good catch!

**Comment by tchx84** [comment]
I will address the tooltip issue with a separate PR.

**Pull request merged**
