### PR TITLE
widgets: Fix regression with header bar controls placement

### LINKED ISSUE #200: Titlebar buttons incorrectly placed when buttons are set in the left
image

The title bar buttons (<kbd>X</kbd> and <kbd>-</kbd>) are placed in the left side of the middle when it should be in the far left.

### PR DESCRIPTION
**Pull request by tchx84**
Closes #200

### CODE REVIEW

**Comment by tchx84** [comment]
@TheEvilSkeleton can you help me test this? :)

**Comment by TheEvilSkeleton** [comment]
@tchx84 it works :)

image

**Comment by TheEvilSkeleton** [comment]
@tchx84 btw you did a typo in the description:

```diff
- Cloaes #200
+ Closes #200
```

**Comment by tchx84** [comment]
> @tchx84 btw you did a typo in the description:
> 
> ```diff
> - Cloaes #200
> + Closes #200
> ```

good catch!

**Pull request merged**
