### PR TITLE
aboutDialog: Add A6GibKm to credits

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@A6GibKm what name should I use here?

**Comment by A6GibKm** [comment]
I PM'd you on matrix

**Comment by A6GibKm** [comment]
I don't think my contributions are significant enough to warrant a spot in the about dialog. But if you must use `Maximiliano Sandoval <msandova@gnome.org>`.

**Comment by tchx84** [comment]
> I don't think my contributions are significant enough to warrant a spot in the about dialog. But if you must use `Maximiliano Sandoval <msandova@gnome.org>`.

Well, deciding what is "enough" is one of the perks of being the owner ;) merged on [1540a0f](https://github.com/tchx84/Flatseal/commit/1540a0f341ecdbe2715d6e1a016872caab97b81f)

**Pull request closed without merging**
