### PR TITLE
window: Set proper accelerator for activating search

### LINKED ISSUE #274: Typing after launch no longer searches for apps
I might be misremembering but I'm fairly sure before 1.7.0 typing right after launch would search for the app. Either way this is not the case on 1.7.0, and I'd like to request this because the first thing you do after opening Flatseal is find the app you need.

### PR DESCRIPTION
**Pull request by tchx84**
Closes #274

### CODE REVIEW

**Comment by tchx84** [comment]
@YaLTeR I prefer not to activate the search entry by default, so I think an extra ctrl+f could be a good-enough compromise.

What do you think?

**Comment by YaLTeR** [comment]
Hm, why not activate it by default? I think type to search is one of the common patterns in GNOME (e.g. if you open Settings and type you'll start searching). One argument I see is that type to search should search preferences within the currently selected app, which is why I'm suggesting only focusing app search once at launch—when you want to use it. Perhaps even start with an empty state rather than selecting the first app in the list at launch, this way it's clear that typing will search for apps (since there are no preferences visible).

**Comment by tchx84** [comment]
> Hm, why not activate it by default?

If I activate it by default, then I need to focus it on default (or it wouldn't make much sense, as it would still require one step to use it), and by focusing by default creates this scenario where I launch Flatseal on my phone, the virtual keyboard takes half of my screen when I just want to browse for an app that would be much easier to find if I had that screen space available.

>I think type to search is one of the common patterns in GNOME (e.g. if you open Settings and type you'll start searching). 

I haven't looked at detail, but I suspected there could be a difference between apps that don't have free-form text entries, at the top-level window, e.g. settings, and those that do, e.g. like Flatseal. But maybe there's a simple approach to this? Without having to mess with keyboard events that later creates another issue.

Would you be interested in looking into it?

Also, note that `ctrl+f` is quite a common pattern as well.

> One argument I see is that type to search should search preferences within the currently selected app, which is why I'm suggesting only focusing app search once at launch.

I haven't really thought about this (also see my comment above), but have you considered how this could work on a phone?

**Comment by YaLTeR** [comment]
Oh, hmm, yeah, I don't have any experience in GTK development for phones.

Maybe then empty initial state + type to search which searches apps on the empty state and preferences on non-empty state will work?

**Comment by tchx84** [comment]
> Oh, hmm, yeah, I don't have any experience in GTK development for phones.
> 
> Maybe then empty initial state + type to search which searches apps on the empty state and preferences on non-empty state will work?

Well, I think that we need to tackle the issues separately, and and then adapt the UI when a good design emerges. Let's continue the "search permissions" topic here https://github.com/tchx84/Flatseal/issues/125 (which has been opened for a while now, mostly due for the lack of clarity on the design side of things).

As for this PR, it addresses the ability of initiating search using the keyboard with the widely common `ctrl+f` accelerator. So ill merge this for now.

**Pull request merged**
