### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@AsciiWolf @ovari @Vistaus @eson57 @cho2 @TheEvilSkeleton @MiloCasagrande @BigmenPixel0 @stenosis @juxuanu @Garbulix @usnotv In case you have the time.

Note that I introduced a few mnemonics on menus and buttons, and we should avoid repearting the same letters for activation (see Spanish translation for the menu items, for example).

**Comment by AsciiWolf** [comment]
#361

**Comment by cho2** [comment]
https://github.com/tchx84/Flatseal/pull/365

**Comment by TheEvilSkeleton** [comment]
Hmm... I noticed there is no translation for French. Perhaps I could submit an MR? I don't know other languages.

**Comment by TheEvilSkeleton** [comment]
https://github.com/tchx84/Flatseal/pull/367

**Pull request merged**
