### PR TITLE
window: Make menu popover easier to use on compact mode

### LINKED ISSUE #131: mobile: Menu popover too small
See https://github.com/tchx84/flathub-mobile/blob/master/README.md

### PR DESCRIPTION
**Pull request by tchx84**
Closes #131

### CODE REVIEW

**Comment by tchx84** [comment]
Hi @bertob,

I did some research over the weekend on Flathub applications on a real phone, and found some [pain points](https://github.com/tchx84/flathub-mobile/blob/master/README.md#common-pain-points) I want to address.

As a short-term solution, I am thinking to make the menu-popover items a little bigger when the app is "folded", but I am wondering if there's something more conventional... any suggestions welcome.

Thanks for all the help so far :)

EDIT: this is how it looks with this hack:

image

**Comment by bertob** [comment]
I don't think it needs to be that drastic, a little bit more padding across the board (i.e. not only when it's folded) would be enough.

Android and iOS have very similar menus, and the entries aren't that much more widely spaced than ours: https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/

**Comment by tchx84** [comment]
> I don't think it needs to be that drastic,

Drastic is my second name :laughing: 

>a little bit more padding across the board (i.e. not only when it's folded) would be enough.
 
Done.

> Android and iOS have very similar menus, and the entries aren't that much more widely spaced than ours: https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/

I see, interesting. Thanks for the reference.

**Comment by bertob** [comment]
> >    a little bit more padding across the board (i.e. not only when it's folded) would be enough.

> Done.

Screenshot?

**Comment by tchx84** [comment]
> > > a little bit more padding across the board (i.e. not only when it's folded) would be enough.
> 
> > Done.
> 
> Screenshot?

image

**Comment by bertob** [comment]
Looks good :+1:

**Pull request merged**
