### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@AsciiWolf @ovari @Vistaus @eson57 @cho2 @MiloCasagrande @stenosis @usnotv @juxuanu for whenever you have the time :)

**Comment by juxuanu** [comment]
https://github.com/tchx84/Flatseal/pull/320

**Comment by AsciiWolf** [comment]
#321

**Comment by ovari** [comment]
Can the translations please be hosted on Weblate? What do you think? Thank you

**Comment by cho2** [comment]
#322

**Comment by Vistaus** [comment]
> Can the translations please be hosted on Weblate? What do you think? Thank you

I don't mind the GitHub way, but Weblate and Transifex are good alternatives. 🙂

**Comment by tchx84** [comment]
> Can the translations please be hosted on Weblate? What do you think? Thank you

I don't mind as long as:

1. It has a good trust model, e.g. it can make PRs instead of having to grant full push access.
2. It doesn't hide individual contributors credits, which is very important for me.

If someone wants to set this up, we can try it! Please take the lead.

**Pull request merged**
