### PR TITLE
Update hu.po

### PR DESCRIPTION
**Pull request by ovari**
Should
`msgid "Reset this application permissions"`
be
`msgid "Reset this application’s permissions"`

### CODE REVIEW

**Comment by ovari** [comment]
@tchx84 can you please accept this pull request? Thank you

**Comment by tchx84** [comment]
> Should
> `msgid "Reset this application permissions"`
> be
> `msgid "Reset this application’s permissions"`

Good catch but, to simplify this PR, I would recommend to just translate the current strings.

The proper fix would be to correct the string from the source and then update the .pot and po files.

**Comment by ovari** [comment]
Can you please accept the hu file?

The English update can be done later.

**Review by tchx84 — APPROVED** [review]
Looks good. Thanks!

Ill try it locally first a bit later today and then merge it.

**Comment by ovari** [comment]
Can we delete our fork?

**Comment by tchx84** [comment]
> Can we delete our fork?

Sure, I already a have a local copy of your commit.

**Comment by ovari** [comment]
Thanks.

Please let us know when it is on Flathub.

**Pull request merged**
