### PR TITLE
Update Ukrainian localization

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by tchx84 — CHANGES_REQUESTED** [review]
Thanks @Vovkiv , it seems you updated an older version of this file... can you apply your changes to the latest version?

**Comment by ghost** [comment]
Now I think everything should be alright?
I just fixed newly added strings + some unrelated changes.

Or wait, I think I can quickly fix.

**Comment by ghost** [comment]
Now, I think, everything should be correct.

**Review by tchx84 — APPROVED** [review]
@Vovkiv thanks, working now !

**Pull request merged**
