### PR TITLE
WIP: Handyfication

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@TheEvilSkeleton want to give this a try? :)

**Comment by TheEvilSkeleton** [comment]
@tchx84 this looks so much better!

I love how it looks and how the content is highlighted when hovered.

There's one problem however: it's rough when resizing:


https://user-images.githubusercontent.com/50847364/110946358-c2718d80-830c-11eb-85ed-21135a648f0c.mp4

As you can see, when resizing, since it goes in the "mobile" mode, what's inside the content changes that way, which produces a weird animation.

Other than that, I love the new look.

**Comment by tchx84** [comment]
> As you can see, when resizing, since it goes in the "mobile" mode, what's inside the content changes that way, which produces a weird animation.

Yeah, I am aware. It's needed to prevent more serious issue (try removing the geddan-effect commit, and you will see). So, we will have to live with that hah.

**Comment by TheEvilSkeleton** [comment]
It's not a big deal. It's barely noticeable to begin with. I had to force myself to look through inconsistencies, and apparently that was a thing in previous versions as well.

I think everything works well.

**Comment by tchx84** [comment]
> It's not a big deal. It's barely noticeable to begin with. I had to force myself to look through inconsistencies, and apparently that was a thing in previous versions as well.
> 
> I think everything works well.

Awesome, thanks for testing ;)

**Comment by TheEvilSkeleton** [comment]
One minor issue, when scrolling, it doesn't change the cursor on my laptop:

https://user-images.githubusercontent.com/50847364/110948236-18dfcb80-830f-11eb-95ed-d121640f1830.mp4

Edit: Maybe because it changes cursors? I tried it on the stable version and the cursor changes.

Nevermind. It's not a Flatseal issue.

**Comment by TheEvilSkeleton** [comment]
@tchx84 yeah, sorry for the misinformation. That was a GNOME Builder bug. I installed this version and everything works fine.

**Comment by tchx84** [comment]
> @tchx84 yeah, sorry for the misinformation. That was a GNOME Builder bug. I installed this version and everything works fine.

:laughing: no worries, you keep trying to break it :) it helps a lot

**Comment by TheEvilSkeleton** [comment]
@tchx84 everything works without any problem. I tried breaking it in many ways but this app is just so well done.

**Comment by tchx84** [comment]
> @tchx84 everything works without any problem. I tried breaking it in many ways but this app is just so well done.

:+1:

**Pull request merged**
