### PR TITLE
Update Spanish and Brazilian Portuguese translations

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@AsciiWolf @ovari @Vistaus @MiloCasagrande @eson57 @cho2 @stenosis two new strings this time :) can you help me ?

**Comment by ovari** [comment]
@tchx84 done at https://github.com/tchx84/Flatseal/pull/151. Thank you

**Comment by Vistaus** [comment]
Done #152 :)

**Comment by ovari** [comment]
@Vistaus unfortunately #151 still shows as not done.
https://github.com/tchx84/Flatseal/blob/master/po/hu.po#L372-L378

**Comment by Vistaus** [comment]
@ovari My PR is #152.

**Comment by tchx84** [comment]
> @AsciiWolf @ovari @Vistaus @MiloCasagrande @eson57 @cho2 @stenosis two new strings this time :) can you help me ?

Thanks to those who contributed so far :) haha

**Pull request merged**
