### PR TITLE
CI: add a flatpak job

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
builds & uploads an artifact to make testing the app very simple from the user

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
The CI won't start until this gets merged & either a new PR is created/rebased on top of that or a new commit is pushed to master. Here's the CI in action on my fork https://github.com/bilelmoussaoui/Flatseal/pull/1/checks?check_run_id=1288177617

**Comment by tchx84** [comment]
Absolute awesomeness :)

Think something like this could be also used for running the jasmine tests? see https://github.com/tchx84/Flatseal/issues/108

**Comment by bilelmoussaoui** [comment]
A different job could be added yes

**Comment by tchx84** [comment]
> A different job could be added yes

Greal, ill ask more details in chat ;)

Thanks for this!

**Comment by bilelmoussaoui** [comment]
Actually, I've just  checked, the tests are run through meson which would require some work from the action side and it should just work later :) I don't want to tie it to meson like we do with the gitlab ci template we have at gnome to make sure other apps adopt flatpak :p 
so I will have to figure out that first

**Pull request merged**
