### PR TITLE
manifest: remove libhandy

### PR DESCRIPTION
**Pull request by Lctrs**
it's available in the runtime now

### CODE REVIEW

**Comment by tchx84** [comment]
Thanks, can you confirm the exact version present in the gnome/40 runtime?

**Comment by Lctrs** [comment]
1.2.0

**Comment by Lctrs** [comment]
https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/gnome-40/elements/sdk/libhandy.bst

**Comment by tchx84** [comment]
> 1.2.0

Ok, let's put this PR on hold until it's updated to 1.2.1? so we don't regress anything :)

Thanks!

**Comment by tchx84** [comment]
> https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/gnome-40/elements/sdk/libhandy.bst

Perfect, let's keep an eye on it, and we get rid of this once the version matches.

**Comment by tchx84** [comment]
@Lctrs can you check if this change was released? https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/gnome-40/elements/sdk/libhandy.bst#L4

If it's already available then we can update this PR, and merge it before the next Flatseal on Friday.

**Comment by Lctrs** [comment]
Not released yet. FYI, You can check for a release yourself by looking at the tags in the repo.

**Comment by Lctrs** [comment]
@tchx84, it has been released.

**Comment by tchx84** [comment]
> @tchx84, it has been released.

Excellent! Thanks.

**Comment by tchx84** [comment]
> @tchx84, it has been released.

What name should I use for mentioning your contribution in Flatseal's credits?

**Pull request merged**
