### PR TITLE
feature: Take global overrides into account

### LINKED ISSUE #351: Flatseal shows wrong permissions
I've `global` overrides where I fix common faults like `filesystem=home;` disable X11.
Unfortunately flatseal then shows wrong (not the actual) permissions for my apps and makes it harder to re-enable X11 for example.

While #210 is about adding editing support for `global`, this ticket only deals with the fact that global overrides are taken into account when reading app permissions (like `flatpak info -M <APP>`).

### PR DESCRIPTION
**Pull request by Arxcis**
#### Why?

- Fixes #351 
- Relates to #210 
- From `man flatpak-override`:
    >If the application id is not specified then the overrides affect all applications, but the per-application overrides can override the global overrides.

#### TODO - Update implementation of updateProxyProperty() and updateFromProxyProperty() in all models
- [ ] models/filesystemsOther.js
- [ ] models/persistent.js
- [ ] models/sessionBus.js
- [x] models/shared.js
- [ ] models/variables.js

#### TODO - Pass all tests

As expected, the models which has not been implemented yet, fails the tests:
```
1) Model loads global overrides

  Expected '~/test' to equal '~/test;~/global'.
    @/github/workspace/tests/src/testModels.js:205:47
    run@resource:///org/gnome/gjs/modules/script/mainloop.js:36:22
    @/usr/local/libexec/jasmine-gjs/jasmine-runner:42:9


  Expected 'org.test.Service-1' to equal 'org.test.Service-1;org.global.Service-1'.
    @/github/workspace/tests/src/testModels.js:206:42
    run@resource:///org/gnome/gjs/modules/script/mainloop.js:36:22
    @/usr/local/libexec/jasmine-gjs/jasmine-runner:42:9


  Expected 'org.test.Service-2' to equal 'org.test.Service-2;org.global.Service-2'.
    @/github/workspace/tests/src/testModels.js:207:41
    run@resource:///org/gnome/gjs/modules/script/mainloop.js:36:22
    @/usr/local/libexec/jasmine-gjs/jasmine-runner:42:9


  Expected 'org.test.Service-3' to equal 'org.test.Service-3;org.global.Service-3'.
    @/github/workspace/tests/src/testModels.js:208:41
    run@resource:///org/gnome/gjs/modules/script/mainloop.js:36:22
    @/usr/local/libexec/jasmine-gjs/jasmine-runner:42:9


  Expected 'org.test.Service-4' to equal 'org.test.Service-4;org.global.Service-4'.
    @/github/workspace/tests/src/testModels.js:209:40
    run@resource:///org/gnome/gjs/modules/script/mainloop.js:36:22
    @/usr/local/libexec/jasmine-gjs/jasmine-runner:42:9


  Expected '.test' to equal '.global'.
    @/github/workspace/tests/src/testModels.js:210:40
    run@resource:///org/gnome/gjs/modules/script/mainloop.js:36:22
    @/usr/local/libexec/jasmine-gjs/jasmine-runner:42:9


  Expected 'TEST=yes' to equal 'TEST=global'.
    @/github/workspace/tests/src/testModels.js:211:39
    run@resource:///org/gnome/gjs/modules/script/mainloop.js:36:22
    @/usr/local/libexec/jasmine-gjs/jasmine-runner:42:9
```

### CODE REVIEW

**Comment by tchx84** [comment]
Hey @Arxcis , thanks for giving this a try.

 Sadly, this isn't as simple;

1. This needs to be implemented in _every_ permission _individually_ (not only the "shared" permission, e.g. src/models/*.js). None of these models take "globals" into account for the permissions merging logic (which isn't the same as just calling `loadFromKeyFile(overrides=false)` twice).
2. Leave _all_ unrelated fixes out, or this will be impossible to review.
3. Keep existing tests untouched, to check for regressions.
4. Add a new test to check the global overrides condition for every permission.

**Comment by Arxcis** [comment]
Thank you @tchx84!  I was hoping for this kind of review. I thought it was too simple as well. Your feedback was clear and easy to understand👍

Now I will change this PR to a draft, until I think it is ready again.

The fix included in this PR, is relevant to make the global overrides show correctly, but I can move the fix to a separate mini PR, no problem👍

I will also try as much as possible to avoid unecessary line changes🙏

I will try to write a new failing test, and leave existing tests untouched, as you said.

**Comment by Arxcis** [comment]
Hey @tchx84, I got one quick question. Do you think it makes sense to merge global overrides into `this._originals` as I have done in this PR so far?
```js
this._originals  // <-- apps/APP_ID/current/active/metafile + overrides/global
this._overrides  // <-- overrides/APP_ID
```
...or would it be better to introduce a new member-variable in the models called `this._globals`?
```js
this._originals   // <-- apps/APP_ID/current/active/metafile
this._globals     // <-- overrides/global
this._overrides   // <-- overrides/APP_ID
```

**Comment by Arxcis** [comment]
Closing PR, as there is a lot more work until ready for review.

**Comment by tchx84** [comment]
> Hey @tchx84, I got one quick question. Do you think it makes sense to merge global overrides into `this._originals` as I have done in this PR so far?
> 
> ```js
> this._originals  // <-- apps/APP_ID/current/active/metafile + overrides/global
> this._overrides  // <-- overrides/APP_ID
> ```
> 
> ...or would it be better to introduce a new member-variable in the models called `this._globals`?
> 
> ```js
> this._originals   // <-- apps/APP_ID/current/active/metafile
> this._globals     // <-- overrides/global
> this._overrides   // <-- overrides/APP_ID
> ```

More likely the second (this._globals), because, I assume one of the permission models will require some weird merging logic that requires differentiating each case separately.

Also, keep focusing on the "shared" permission first, and make it work with this._globals, because it's the simplest model. Write the separate test. Then, we review it, and we can move on to another permission model (and repeat the process one by one). But we will know the core elements after the first one gets done right.

**Comment by tchx84** [comment]
> > Hey @tchx84, I got one quick question. Do you think it makes sense to merge global overrides into `this._originals` as I have done in this PR so far?
> > ```js
> > this._originals  // <-- apps/APP_ID/current/active/metafile + overrides/global
> > this._overrides  // <-- overrides/APP_ID
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...or would it be better to introduce a new member-variable in the models called `this._globals`?
> > ```js
> > this._originals   // <-- apps/APP_ID/current/active/metafile
> > this._globals     // <-- overrides/global
> > this._overrides   // <-- overrides/APP_ID
> > ```
> 
> More likely the second (`this._globals`), because, I assume one of the permission models will require some weird merging logic that requires differentiating each case separately.
> 
> Also, keep focusing on the "shared" permission first, and make it work with `this._globals`, because it's the simplest model. Write the separate test. Then, we review it, and we can move on to another permission model (and repeat the process one by one). But we will know the core elements after the first one gets done right.

**Comment by tchx84** [comment]
@Arxcis remember the comments I made earlier, try to focus on getting shared.js model work first, reduce the noise.

**Comment by Arxcis** [comment]
> @Arxcis remember the comments I made earlier, try to focus on getting shared.js model work first, reduce the noise.

Sure :+1: I have focused on `shared.js` first and foremost. I will wait for your review, before doing anything more.

**Comment by spikespaz** [comment]
This needs to be bumped. Bump.

**Comment by tchx84** [comment]
I started working on this on a separate branch, will publish it soon.

**Pull request closed without merging**
