### PR TITLE
help: Add offline documentation

### LINKED ISSUE #229: Offline documentation
We could move our current doc to:
1. http://yelp.io/tools/
2. http://projectmallard.org/ 
3. and, _eventually_, translate it too.

Here's an very nice example https://github.com/alexhuntley/Plots/tree/main/help/C

### PR DESCRIPTION
**Pull request by tchx84**
Closes #229

### CODE REVIEW

**Comment by tchx84** [comment]
@TheEvilSkeleton this is just a functional empty shell, is this something you would be interested in?

**Comment by TheEvilSkeleton** [comment]
@tchx84 how easy/difficult is this approach going to be? From the [example](https://github.com/alexhuntley/Plots/tree/main/help/C) you've provided at #229, it looks like a pain to contribute. I'd prefer using an easy language like Markdown, since it's straightforward, easy to use and easy to understand.

While I do agree that having an offline documentation would be neat, I don't think sacrificing ease of contributions is worth it.

**Comment by tchx84** [comment]
> @tchx84 how easy/difficult is this approach going to be? From the [example](https://github.com/alexhuntley/Plots/tree/main/help/C) you've provided at #229, it looks like a pain to contribute. I'd prefer using an easy language like Markdown, since it's straightforward, easy to use and easy to understand.
> 
> While I do agree that having an offline documentation would be neat, I don't think sacrificing ease of contributions is worth it.

It does support its own MD-like format as well, called [Ducktype](http://projectmallard.org/about/learn/ducktype.html)

Another option could be to just use HTML.

**Comment by TheEvilSkeleton** [comment]
> > @tchx84 how easy/difficult is this approach going to be? From the [example](https://github.com/alexhuntley/Plots/tree/main/help/C) you've provided at #229, it looks like a pain to contribute. I'd prefer using an easy language like Markdown, since it's straightforward, easy to use and easy to understand.
> > While I do agree that having an offline documentation would be neat, I don't think sacrificing ease of contributions is worth it.
> 
> It does support its own MD-like format as well, called [Ducktype](http://projectmallard.org/about/learn/ducktype.html)
> 
> Another option could be to just use HTML.

If it's Markdown, then I'm all for it. Can you link me to the documentation on how/where to get started?

**Comment by tchx84** [comment]
> > > @tchx84 how easy/difficult is this approach going to be? From the [example](https://github.com/alexhuntley/Plots/tree/main/help/C) you've provided at #229, it looks like a pain to contribute. I'd prefer using an easy language like Markdown, since it's straightforward, easy to use and easy to understand.
> > > While I do agree that having an offline documentation would be neat, I don't think sacrificing ease of contributions is worth it.
> > 
> > 
> > It does support its own MD-like format as well, called [Ducktype](http://projectmallard.org/about/learn/ducktype.html)
> > Another option could be to just use HTML.
> 
> If it's Markdown, then I'm all for it. Can you link me to the documentation on how/where to get started?

It's a markdown language, but is not MD. Check this out [Ducktype](http://projectmallard.org/about/learn/ducktype.html)

**Comment by tchx84** [comment]
> > > > @tchx84 how easy/difficult is this approach going to be? From the [example](https://github.com/alexhuntley/Plots/tree/main/help/C) you've provided at #229, it looks like a pain to contribute. I'd prefer using an easy language like Markdown, since it's straightforward, easy to use and easy to understand.
> > > > While I do agree that having an offline documentation would be neat, I don't think sacrificing ease of contributions is worth it.
> > > 
> > > 
> > > It does support its own MD-like format as well, called [Ducktype](http://projectmallard.org/about/learn/ducktype.html)
> > > Another option could be to just use HTML.
> > 
> > 
> > If it's Markdown, then I'm all for it. Can you link me to the documentation on how/where to get started?
> 
> It's a markdown language, but is not MD. Check this out [Ducktype](http://projectmallard.org/about/learn/ducktype.html)

Another option could be something like this https://www.kite.com/python/examples/2545/markdown-convert-markdown-text-to-html (MD to HTML)... but I don't know what yelp/help specific features we would be missing.

e.g. localization.

**Comment by TheEvilSkeleton** [comment]
Just looked through the [Yelp](https://wiki.gnome.org/Apps/Yelp) page a bit. It's really outdated unfortunately.

**Comment by TheEvilSkeleton** [comment]
@tchx84 do you know where to get started? I'm a bit lost to be honest.

**Comment by tchx84** [comment]
> @tchx84 do you know where to get started? I'm a bit lost to be honest.

have you read http://projectmallard.org/about/learn/ducktype.html ?

**Comment by TheEvilSkeleton** [comment]
> > @tchx84 do you know where to get started? I'm a bit lost to be honest.
> 
> have you read http://projectmallard.org/about/learn/ducktype.html ?

I just did. It doesn't look hard to understand Ducktype. Do I need to PR and add an `index.duck` file at the root of the repo?

**Comment by tchx84** [comment]
> > > @tchx84 do you know where to get started? I'm a bit lost to be honest.
> > 
> > 
> > have you read http://projectmallard.org/about/learn/ducktype.html ?
> 
> I just did. It doesn't look hard to understand Ducktype. Do I need to PR and add an `index.duck` file at the root of the repo?

Alright, let me try to set up the basics for Ducktype and we continue from there.

**Comment by TheEvilSkeleton** [comment]
Just curious, are you going to remove https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md ?

**Comment by tchx84** [comment]
> Just curious, are you going to remove https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md ?

Not for now at least, in fact I created this https://github.com/tchx84/Flatseal/pull/239

**Comment by tchx84** [comment]
So, after doing some experiments, I think I am going with this:

1. keep DOCUMENTATION.md as the souce file for our docs.
2. and simply convert it to HTML for the offline version.

Now I simply used Apostrophe to generate this one, but I could also make it auto generated (I checked Apostrophe's code and is using pypandoc).

I think is a fair trade off, and one easy win.

**Comment by tchx84** [comment]
@TheEvilSkeleton give it a try!

**Comment by TheEvilSkeleton** [comment]
@tchx84 it's looking great!

**Comment by TheEvilSkeleton** [comment]
@tchx84 reminder that you'll need to update the portals category from https://github.com/tchx84/Flatseal/pull/239.

**Comment by tchx84** [comment]
> @tchx84 reminder that you'll need to update the portals category from #239.

of course :)  it's planned for monday, yesterday we had GNOME Latam and I am supe tired lol

**Comment by TheEvilSkeleton** [comment]
I hope you had a good time.

**Pull request merged**
