### PR TITLE
Add more permissions and polish a few related things

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@MiloCasagrande @stenosis @Vistaus @AsciiWolf @ovari I added a few new strings in this PR. I used a translator to have something in the meantime, but I would appreciate if you could take a look and polish whatever you find.

**Comment by MiloCasagrande** [comment]
Seems fine to me, thanks for the heads up!

**Comment by Vistaus** [comment]
Mostly good, but I made 2 small changes for which I opened a new PR :)

**Comment by AsciiWolf** [comment]
Looks good, thanks!

**Pull request merged**
